# https://rust-lang.github.io/rustfmt/?version=master&search=

brace_style="PreferSameLine"
fn_args_layout="Compressed"
format_code_in_doc_comments=true
max_width=100
# merge_imports=false
normalize_doc_attributes=true
overflow_delimited_expr=true
struct_field_align_threshold=20
trailing_semicolon=false
use_field_init_shorthand=true
where_single_line=true
